## config/sample_pn2.yaml
hydra:
  run:
    dir: .
  output_subdir: null

defaults:
  - _self_
  - diffuser: null
  - model: null
  - task: null

dataset_name: multidex # ['multidex', 'dexgraspnet', 'egad']
data_root: /home/cli/AAAA/DexDiffuser/dexdiffuser_data

sampler_bps_ckpt_pth: /home/cli/AAAA/DexDiffuser/ckpts/sampler/model_200.pth
sampler_pn2_ckpt_pth: pass
evaluator_ckpt_pth: /home/cli/AAAA/DexDiffuser/ckpts/evaluator/model_20.pth

eval_dir: outputs
exp_name: null
exp_dir: ${exp_name}
guid_scale: null #[null, 1]

cam_views: [0,1,2,3,4,5,6,7,8,9]
num_sample: 20
slurm: false
gpu: 0
vis_type: null # ['html', 'png', 'glb']

task:
  dataset:
    object_root: data/shape
    data_root: data/shape